'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFile, execFileSync, spawn } = require('node:child_process')
const { promisify } = require('node:util')

test('keep-awake lifecycle is idempotent and preserves unrelated or reused processes', { skip: process.platform !== 'darwin' }, async t => {
  const state = fs.mkdtempSync(path.join(os.tmpdir(), 'toolkit-awake-'))
  const awake = path.join(state, 'agent-awake'), sleep = path.join(state, 'agent-sleep')
  const aliases = ['paseo-awake', 'paseo-sleep'].map(name => path.join(state, name))
  const pidFile = path.join(state, 'agent-toolkit/caffeinate.pid')
  for (const file of [awake, sleep, ...aliases]) fs.symlinkSync(path.join(__dirname, 'agent-awake'), file)
  const run = file => execFileSync(file, { env: { ...process.env, XDG_STATE_HOME: state }, encoding: 'utf8' })
  const other = spawn('/usr/bin/caffeinate', ['-i'], { stdio: 'ignore' })
  t.after(() => { try { run(sleep) } finally { other.kill(); fs.rmSync(state, { recursive: true, force: true }) } })

  assert.match(run(awake), /Keeping the Mac awake/)
  const original = fs.readFileSync(pidFile, 'utf8')
  const pid = Number(original.split('\n')[0])
  process.kill(pid, 0)
  assert.match(run(awake), /Already keeping/)
  assert.equal(fs.readFileSync(pidFile, 'utf8'), original)
  const concurrent = await Promise.all(Array.from({ length: 6 }, () => promisify(execFile)(awake, { env: { ...process.env, XDG_STATE_HOME: state } })))
  for (const result of concurrent) assert.match(result.stdout, /Already keeping/)
  assert.equal(fs.readFileSync(pidFile, 'utf8'), original)
  assert.match(run(aliases[1]), /Stopped keep-awake/)
  assert.equal(fs.existsSync(pidFile), false)
  process.kill(other.pid, 0)
  assert.match(run(sleep), /already stopped/)

  fs.writeFileSync(pidFile, `${other.pid}\nwrong start time\n`)
  assert.match(run(sleep), /already stopped/)
  process.kill(other.pid, 0)
  assert.equal(fs.existsSync(pidFile), false)
  const unrelated = spawn('/bin/sleep', ['30'], { stdio: 'ignore' })
  t.after(() => unrelated.kill())
  const start = execFileSync('/bin/ps', ['-p', String(unrelated.pid), '-o', 'lstart='], { encoding: 'utf8' }).trimEnd()
  fs.writeFileSync(pidFile, `${unrelated.pid}\n${start}\n`)
  assert.match(run(sleep), /already stopped/)
  process.kill(unrelated.pid, 0)

  fs.writeFileSync(pidFile, 'invalid PID\n')
  const deadPid = execFileSync('/bin/sh', ['-c', 'echo $$'], { encoding: 'utf8' }).trim()
  fs.writeFileSync(path.join(state, 'agent-toolkit/caffeinate.lock'), `${deadPid}\n`)
  assert.match(run(aliases[0]), /Keeping the Mac awake/)
  assert.notEqual(fs.readFileSync(pidFile, 'utf8'), 'invalid PID\n')
  assert.match(run(sleep), /Stopped keep-awake/)
})
