const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')

// Run the real installer with isolated homes and offline client/dependency stubs.
test('installation recovers dangling Toolkit account links but preserves unrelated links', () => {
  const source = path.resolve(__dirname, '../..')
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'install-migration-'))
  const repo = path.join(fixture, 'repo')
  const bin = path.join(fixture, 'bin')
  fs.cpSync(source, repo, { recursive: true, filter: entry => !['.git', 'node_modules', 'vendor'].includes(path.basename(entry)) })
  fs.mkdirSync(bin)
  fs.mkdirSync(path.join(repo, 'vendor/agent-project-blueprint/distribution'), { recursive: true })
  fs.writeFileSync(path.join(repo, 'vendor/agent-project-blueprint/distribution/bootstrap-questionnaire.json'), '{}')
  for (const relative of ['shared/agent-safety', 'shared/pi-web-access']) fs.symlinkSync(path.join(source, relative, 'node_modules'), path.join(repo, relative, 'node_modules'), 'dir')
  fs.symlinkSync(process.execPath, path.join(bin, 'node'))
  fs.writeFileSync(path.join(bin, 'npm'), '#!/bin/sh\nexit 0\n', { mode: 0o700 })
  const version = fs.readFileSync(path.join(source, 'shared/ponytail/VERSION'), 'utf8').trim()
  fs.writeFileSync(path.join(bin, 'claude'), `#!/bin/sh\ncase "$*" in\n  "plugin list --json") echo '[{"id":"ponytail@ponytail","scope":"user","enabled":true,"version":"${version}"}]' ;;\n  "plugin marketplace list --json") echo '[]' ;;\nesac\n`, { mode: 0o700 })
  fs.writeFileSync(path.join(bin, 'codex'), '#!/bin/sh\ncase "$*" in\n  "plugin marketplace list --json") echo \'{"marketplaces":[]}\' ;;\nesac\n', { mode: 0o700 })
  fs.writeFileSync(path.join(bin, 'pi'), '#!/bin/sh\nexit 0\n', { mode: 0o700 })
  fs.writeFileSync(path.join(bin, 'paseo'), '#!/bin/sh\necho 0.10.3\n', { mode: 0o700 })
  for (const owned of [true, false]) {
    const home = path.join(fixture, owned ? 'owned' : 'unrelated')
    const paseoHome = path.join(home, 'selected-paseo-home')
    fs.mkdirSync(paseoHome, { recursive: true })
    const paseoConfig = path.join(paseoHome, 'config.json')
    const originalPaseo = '{"version":1,"daemon":{"appendSystemPrompt":"User-owned prompt"},"log":{"level":"warn"}}\n'
    fs.writeFileSync(paseoConfig, originalPaseo)
    const paseoSkill = path.join(home, '.agents/skills/paseo/SKILL.md')
    fs.mkdirSync(path.dirname(paseoSkill), { recursive: true })
    fs.writeFileSync(paseoSkill, 'Official Paseo skill fixture')
    const rules = path.join(home, '.codex-accounts/business/rules')
    fs.mkdirSync(rules, { recursive: true })
    const target = path.join(home, '.codex/rules/agent-safety.rules')
    const unrelated = path.join(home, 'user-policy.rules')
    fs.writeFileSync(unrelated, 'user-owned policy')
    const link = path.join(rules, 'agent-safety.rules')
    fs.symlinkSync(owned ? target : unrelated, link)
    const env = { PATH: `${bin}:/usr/bin:/bin`, HOME: home, TMPDIR: fixture, XDG_CONFIG_HOME: path.join(home, '.config'), XDG_DATA_HOME: path.join(home, '.local/share') }
    const result = spawnSync('/bin/bash', [path.join(repo, 'install.sh')], { cwd: repo, env, encoding: 'utf8', timeout: 30000 })
    assert.equal(fs.readFileSync(paseoConfig, 'utf8'), originalPaseo, 'the default installer must not configure Paseo')
    if (owned) {
      assert.equal(result.status, 0, result.stdout + result.stderr)
      assert.equal(fs.existsSync(link), false)
      assert.equal(fs.readFileSync(path.join(home, '.local/bin/pi-yolo'), 'utf8'), fs.readFileSync(path.join(repo, 'shared/agent-safety/agent-yolo'), 'utf8'))
      const backups = fs.readdirSync(path.join(home, '.local/share/agent-toolkit/backups'))
      assert.equal(backups.length, 1)
      assert.equal(fs.readlinkSync(path.join(home, '.local/share/agent-toolkit/backups', backups[0], '.codex-accounts/business/rules/agent-safety.rules')), target)
      const remote = spawnSync('/bin/bash', [path.join(repo, 'install.sh'), '--paseo'], { cwd: repo, env: { ...env, PASEO_HOME: paseoHome, PASEO_HOST: 'tcp://remote.example:6767' }, encoding: 'utf8', timeout: 30000 })
      assert.equal(remote.status, 2)
      assert.match(remote.stderr, /local daemon home/)
      assert.equal(fs.readFileSync(paseoConfig, 'utf8'), originalPaseo)
      const native = spawnSync('/bin/bash', [path.join(repo, 'install.sh'), '--paseo'], { cwd: repo, env: { ...env, PASEO_HOME: paseoHome }, encoding: 'utf8', timeout: 30000 })
      assert.equal(native.status, 0, native.stdout + native.stderr)
      const configured = JSON.parse(fs.readFileSync(paseoConfig, 'utf8'))
      const sharedRules = fs.readFileSync(path.join(repo, 'pi/AGENTS.md'), 'utf8')
      assert.equal(configured.daemon.appendSystemPrompt.split(sharedRules).length, 2)
      assert.ok(configured.daemon.appendSystemPrompt.startsWith('User-owned prompt\n\n'))
      assert.deepEqual(configured.daemon.mcp, { enabled: true, injectIntoAgents: true })
      assert.equal(configured.agents.providers.codex.env.AGENT_TOOLKIT_ORCHESTRATION_HOST, 'paseo')
      assert.equal(configured.agents.providers.claude.env.AGENT_TOOLKIT_ORCHESTRATION_HOST, 'paseo')
      assert.deepEqual(configured.log, { level: 'warn' })
      const backupDirectory = path.join(home, '.local/share/agent-toolkit/backups')
      assert.ok(fs.readdirSync(backupDirectory).some(name => {
        const backup = path.join(backupDirectory, name, 'selected-paseo-home/config.json')
        return fs.existsSync(backup) && fs.readFileSync(backup, 'utf8') === originalPaseo
      }), 'the native instruction installation must back up the original Paseo config')
      assert.match(native.stdout, /reload --json/)
    } else {
      assert.notEqual(result.status, 0)
      assert.match(result.stderr, /refusing to retire unverified symlink/)
      assert.equal(fs.readlinkSync(link), unrelated)
    }
    assert.equal(fs.readFileSync(unrelated, 'utf8'), 'user-owned policy')
    assert.equal(fs.readFileSync(paseoSkill, 'utf8'), 'Official Paseo skill fixture')
  }
})
