const assert = require('node:assert/strict')
const { mkdtempSync, mkdirSync, readFileSync, writeFileSync, realpathSync, renameSync, symlinkSync, rmSync, statSync, chmodSync } = require('node:fs')
const { join } = require('node:path')
const { tmpdir } = require('node:os')
const { execFileSync } = require('node:child_process')
const test = require('node:test')

test('runtime policy authorizes persistent scratch without opening temporary or runtime directories', () => {
  const root = realpathSync(mkdtempSync(join(process.env.AGENT_TOOLKIT_SCRATCH_ROOT || tmpdir(), 'pi-runtime-policy-')))
  try {
    const managed = join(root, 'managed')
    const runtime = join(root, 'runtime')
    const policy = join(managed, 'extensions/pi-permission-system/config.json')
    const output = join(runtime, 'extensions/pi-permission-system/config.json')
    mkdirSync(join(managed, 'extensions/pi-permission-system'), { recursive: true })
    mkdirSync(join(runtime, 'extensions/pi-permission-system'), { recursive: true })
    writeFileSync(policy, readFileSync(join(__dirname, 'pi-permission-system.json')))
    const launcher = readFileSync(join(__dirname, 'agent-yolo'), 'utf8')
    const script = launcher.match(/node - "\$policy" "\$agent_dir\/extensions\/pi-permission-system\/config.json" <<'NODE'\n([\s\S]*?)\nNODE/)[1]
    const env = { ...process.env, HOME: join(root, 'home') }
    const run = () => execFileSync(process.execPath, ['-', policy, output], { input: script, env, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] })
    const scratch = join(env.HOME, 'Code/.agent-toolkit-scratch')
    assert.equal(run(), scratch)
    const config = JSON.parse(readFileSync(output, 'utf8'))
    assert.ok(config.piInfrastructureReadPaths.includes(join(runtime, 'extensions')))
    assert.ok(config.piInfrastructureReadPaths.includes(join(managed, 'extensions')))
    assert.ok(!config.piInfrastructureReadPaths.includes(runtime))
    assert.ok(!config.piInfrastructureReadPaths.includes(managed))
    const reviewRoot = join(managed, 'review-results')
    assert.ok(config.piInfrastructureReadPaths.includes(reviewRoot))
    assert.equal(readFileSync(join(reviewRoot, '.read-probe.txt'), 'utf8'), 'Pi review results read access is available.\n')
    assert.equal(config.permission.external_directory[reviewRoot], undefined)
    assert.ok(!config.piInfrastructureReadPaths.includes(realpathSync(tmpdir())))
    assert.match(launcher, /AGENT_TOOLKIT_REVIEW_ROOT="\$source_agent_dir\/review-results"/)
    assert.match(launcher, /AGENT_TOOLKIT_SCRATCH_ROOT="\$scratch_root"/)
    assert.equal(statSync(scratch).mode & 0o777, 0o700)
    assert.equal(config.permission.external_directory[scratch], 'allow')
    assert.equal(config.permission.external_directory[join(scratch, '*')], 'allow')
    assert.equal(config.permission.external_directory[realpathSync(tmpdir())], undefined)
    assert.equal(config.permission.external_directory[managed], undefined)
    const task = execFileSync('mktemp', ['-d', join(scratch, 'validation.XXXXXX')], { encoding: 'utf8' }).trim()
    writeFileSync(join(task, 'resume.txt'), 'unfinished validation')
    chmodSync(scratch, 0o755)
    assert.equal(run(), scratch)
    assert.equal(statSync(scratch).mode & 0o777, 0o700)
    assert.equal(readFileSync(join(task, 'resume.txt'), 'utf8'), 'unfinished validation')
    renameSync(scratch, `${scratch}-saved`)
    symlinkSync(`${scratch}-saved`, scratch)
    assert.throws(run, /Scratch directory must be a real directory/)
    assert.deepEqual(JSON.parse(readFileSync(output, 'utf8')), config)
    rmSync(scratch)
    renameSync(`${scratch}-saved`, scratch)
    assert.equal(config.permission.bash['rm *'], 'deny')
    assert.equal(config.permission.external_directory['*'], 'deny')
    assert.equal(config.permission.external_directory[join(runtime, 'extensions')], undefined)
    assert.equal(config.permission.path[join(runtime, 'auth.json')], 'deny')
    assert.equal(config.permission.path[join(runtime, 'codex-runtimes', '*', 'auth.json')], 'deny')
    assert.equal(config.permission.path['~/.pi/agent/auth-profiles/*'], 'deny')
    assert.equal(config.permission.path['*.env'], 'deny')
    renameSync(reviewRoot, join(managed, 'saved-reviews'))
    symlinkSync(join(managed, 'saved-reviews'), reviewRoot)
    assert.throws(run, /must not be a symlink/)
    assert.deepEqual(JSON.parse(readFileSync(output, 'utf8')), config)
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})
